// Purpose: Template generators for configuration files
import { ParsedIntent } from '../../types'

export function generatePackageJson(intent: ParsedIntent): string {
    const projectName = intent.siteName.toLowerCase().replace(/\s+/g, '-')

    return `{
  "name": "${projectName}",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "description": "${intent.siteName} - Generated by ProbFixora",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview",
    "test": "vitest"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "lucide-react": "^0.294.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.37",
    "@types/react-dom": "^18.2.15",
    "@vitejs/plugin-react": "^4.2.0",
    "autoprefixer": "^10.4.16",
    "postcss": "^8.4.31",
    "tailwindcss": "^3.3.5",
    "typescript": "^5.2.2",
    "vite": "^5.0.0",
    "vitest": "^0.34.6"
  }
}`
}

export function generateViteConfig(): string {
    return `// Purpose: Vite configuration
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 3000,
    open: true,
  },
})`
}

export function generateTailwindConfig(intent: ParsedIntent): string {
    const isDark = intent.theme === 'dark' || intent.theme === 'amazon'

    return `// Purpose: Tailwind CSS configuration with custom theme
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '${adjustColor(intent.primaryColor, 0.95)}',
          100: '${adjustColor(intent.primaryColor, 0.9)}',
          200: '${adjustColor(intent.primaryColor, 0.8)}',
          300: '${adjustColor(intent.primaryColor, 0.6)}',
          400: '${adjustColor(intent.primaryColor, 0.4)}',
          500: '${intent.primaryColor}',
          600: '${adjustColor(intent.primaryColor, -0.1)}',
          700: '${adjustColor(intent.primaryColor, -0.2)}',
          800: '${adjustColor(intent.primaryColor, -0.3)}',
          900: '${adjustColor(intent.primaryColor, -0.4)}',
        },
        secondary: {
          500: '${intent.secondaryColor}',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}`
}

// Helper to adjust color brightness
function adjustColor(hex: string, amount: number): string {
    const cleanHex = hex.replace('#', '')
    const num = parseInt(cleanHex, 16)

    let r = (num >> 16) + Math.round(255 * amount)
    let g = ((num >> 8) & 0x00FF) + Math.round(255 * amount)
    let b = (num & 0x0000FF) + Math.round(255 * amount)

    r = Math.min(255, Math.max(0, r))
    g = Math.min(255, Math.max(0, g))
    b = Math.min(255, Math.max(0, b))

    return `#${((r << 16) | (g << 8) | b).toString(16).padStart(6, '0')}`
}

export function generateMainTsx(): string {
    return `// Purpose: React application entry point
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`
}

export function generateIndexCss(intent: ParsedIntent): string {
    const isDark = intent.theme === 'dark' || intent.theme === 'amazon'

    return `/* Purpose: Global styles and Tailwind imports */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --color-primary: ${intent.primaryColor};
  }

  html {
    scroll-behavior: smooth;
  }

  body {
    @apply ${isDark ? 'bg-gray-900 text-white' : 'bg-white text-gray-900'} font-sans antialiased;
  }

  ::selection {
    @apply bg-primary-500 text-white;
  }
}

@layer components {
  .btn {
    @apply inline-flex items-center justify-center px-6 py-3 font-semibold rounded-lg
           transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2;
  }

  .btn-primary {
    @apply btn bg-primary-500 text-white hover:bg-primary-600 focus:ring-primary-500;
  }

  .btn-secondary {
    @apply btn border-2 border-gray-300 ${isDark ? 'text-white hover:border-white' : 'text-gray-700 hover:border-gray-500'};
  }

  .section {
    @apply py-16 md:py-24;
  }

  .container {
    @apply max-w-7xl mx-auto px-4 sm:px-6 lg:px-8;
  }

  .heading-xl {
    @apply text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight;
  }

  .heading-lg {
    @apply text-3xl md:text-4xl font-bold tracking-tight;
  }

  .heading-md {
    @apply text-2xl md:text-3xl font-semibold;
  }

  .card {
    @apply ${isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'} rounded-xl border shadow-sm;
  }
}`
}

export function generateAppTsx(intent: ParsedIntent): string {
    const imports: string[] = []
    const components: string[] = []

    // Always include Nav
    imports.push("import Nav from './components/Nav'")
    components.push('      <Nav />')

    // Add sections based on parsed intent
    if (intent.sections.includes('hero')) {
        imports.push("import Hero from './components/Hero'")
        components.push('      <Hero />')
    }

    if (intent.sections.includes('features')) {
        imports.push("import Features from './components/Features'")
        components.push('      <Features />')
    }

    if (intent.sections.includes('pricing')) {
        imports.push("import Pricing from './components/Pricing'")
        components.push('      <Pricing />')
    }

    if (intent.sections.includes('cta')) {
        imports.push("import CTA from './components/CTA'")
        components.push('      <CTA />')
    }

    if (intent.sections.includes('contact')) {
        imports.push("import Contact from './components/Contact'")
        components.push('      <Contact />')
    }

    // Always include Footer
    imports.push("import Footer from './components/Footer'")
    components.push('      <Footer />')

    const isDark = intent.theme === 'dark' || intent.theme === 'amazon'

    return `// Purpose: Main application component
import { useState, useEffect } from 'react'
${imports.join('\n')}

function App() {
  const [isDark, setIsDark] = useState(${isDark})

  useEffect(() => {
    if (isDark) {
      document.documentElement.classList.add('dark')
    } else {
      document.documentElement.classList.remove('dark')
    }
  }, [isDark])

  return (
    <div className="min-h-screen">
${components.join('\n')}
    </div>
  )
}

export default App`
}

export function generateIndexHtml(intent: ParsedIntent): string {
    const title = intent.siteName
    const description = `${intent.siteName} - ${intent.tone} ${intent.industry || 'website'}`

    return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <meta name="description" content="${description}" />
    <meta name="theme-color" content="${intent.primaryColor}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`
}
